import 'dart:typed_data';

import 'package:habit_tracker/core/reports/aggregate_report_usecase.dart';
import 'package:habit_tracker/core/utils/date_range.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

/// Builds a PDF report document from already-computed `ModuleReport`s
/// (`docs/superpowers/specs/04-premium/05-exportable-pdf-csv-reports-
/// IMPLEMENTATION-PLAN.md`) — pure bytes-in/bytes-out (no Flutter
/// widget tree, no bundle/asset loading of its own), so it's testable
/// without a widget test harness. The caller resolves `logoBytes`/
/// `chartImages` (which do need `rootBundle`/`RenderRepaintBoundary`
/// respectively) and passes them in already decoded.
class PdfReportGenerator {
  /// Creates the generator.
  const PdfReportGenerator();

  /// Renders the report. [chartImages] maps a `ModuleReport.moduleId` to
  /// its already-rendered chart PNG bytes; a module with no entry (or
  /// when [chartImages] is `null`) still gets its text summary, just
  /// without an embedded chart image.
  Future<Uint8List> generate({
    required List<ModuleReport> reports,
    required DateRange range,
    required String periodLabel,
    required DateTime generatedAt,
    String? profileName,
    Uint8List? logoBytes,
    Map<String, Uint8List>? chartImages,
  }) async {
    final doc = pw.Document();
    final logo = logoBytes == null ? null : pw.MemoryImage(logoBytes);
    doc.addPage(
      pw.MultiPage(
        footer: (context) => pw.Container(
          alignment: pw.Alignment.center,
          margin: const pw.EdgeInsets.only(top: 8),
          child: pw.Text(
            'Generated by Habit Tracker',
            style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
          ),
        ),
        build: (context) => [
          _buildHeader(logo, periodLabel, range, generatedAt, profileName),
          pw.SizedBox(height: 16),
          for (final report in reports) ...[
            _buildModuleSection(report, chartImages?[report.moduleId]),
            pw.SizedBox(height: 16),
          ],
        ],
      ),
    );
    return doc.save();
  }

  pw.Widget _buildHeader(
    pw.MemoryImage? logo,
    String periodLabel,
    DateRange range,
    DateTime generatedAt,
    String? profileName,
  ) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          children: [
            if (logo != null) ...[
              pw.SizedBox(width: 32, height: 32, child: pw.Image(logo)),
              pw.SizedBox(width: 8),
            ],
            pw.Text(
              'Habit Tracker',
              style: const pw.TextStyle(
                fontSize: 20,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
          ],
        ),
        pw.SizedBox(height: 8),
        pw.Text(
          'Period: $periodLabel '
          '(${range.start.toIso()} to ${range.end.toIso()})',
        ),
        if (profileName != null) pw.Text('Profile: $profileName'),
        pw.Text('Generated: ${generatedAt.toIso8601String()}'),
        pw.Divider(),
      ],
    );
  }

  pw.Widget _buildModuleSection(ModuleReport report, Uint8List? chartImage) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          report.displayName,
          style: const pw.TextStyle(
            fontSize: 16,
            fontWeight: pw.FontWeight.bold,
          ),
        ),
        pw.Text('Longest streak: ${report.longestStreak} days'),
        if (chartImage != null) ...[
          pw.SizedBox(height: 8),
          pw.Container(
            height: 150,
            alignment: pw.Alignment.centerLeft,
            child: pw.Image(pw.MemoryImage(chartImage)),
          ),
        ],
        pw.SizedBox(height: 8),
        pw.Divider(),
      ],
    );
  }
}
