import 'package:habit_tracker/core/l10n/app_localizations.dart';

/// Resolves a bundled city's `nameKey`
/// (`assets/data/prayer_cities.json`) to its localized display name —
/// the asset stores a key, never a raw display string, so the same
/// dataset serves both locales.
String cityDisplayName(AppLocalizations l10n, String nameKey) =>
    switch (nameKey) {
      'cityDhaka' => l10n.cityDhaka,
      'cityChattogram' => l10n.cityChattogram,
      'cityRajshahi' => l10n.cityRajshahi,
      'cityKhulna' => l10n.cityKhulna,
      'cityBarishal' => l10n.cityBarishal,
      'citySylhet' => l10n.citySylhet,
      'cityRangpur' => l10n.cityRangpur,
      'cityMymensingh' => l10n.cityMymensingh,
      'cityGazipur' => l10n.cityGazipur,
      'cityNarayanganj' => l10n.cityNarayanganj,
      'cityCumilla' => l10n.cityCumilla,
      'cityCoxsBazar' => l10n.cityCoxsBazar,
      'cityBogura' => l10n.cityBogura,
      'cityJashore' => l10n.cityJashore,
      'cityDinajpur' => l10n.cityDinajpur,
      'cityKushtia' => l10n.cityKushtia,
      'cityPabna' => l10n.cityPabna,
      'cityTangail' => l10n.cityTangail,
      'cityFaridpur' => l10n.cityFaridpur,
      'cityNoakhali' => l10n.cityNoakhali,
      'cityFeni' => l10n.cityFeni,
      'cityBrahmanbaria' => l10n.cityBrahmanbaria,
      'cityNarsingdi' => l10n.cityNarsingdi,
      'cityManikganj' => l10n.cityManikganj,
      'cityJamalpur' => l10n.cityJamalpur,
      'cityNetrokona' => l10n.cityNetrokona,
      'cityKishoreganj' => l10n.cityKishoreganj,
      'citySatkhira' => l10n.citySatkhira,
      'cityMecca' => l10n.cityMecca,
      'cityMedina' => l10n.cityMedina,
      'cityJeddah' => l10n.cityJeddah,
      'cityRiyadh' => l10n.cityRiyadh,
      'cityDammam' => l10n.cityDammam,
      'cityCairo' => l10n.cityCairo,
      'cityAlexandria' => l10n.cityAlexandria,
      'cityIstanbul' => l10n.cityIstanbul,
      'cityAnkara' => l10n.cityAnkara,
      'cityDubai' => l10n.cityDubai,
      'cityAbuDhabi' => l10n.cityAbuDhabi,
      'cityDoha' => l10n.cityDoha,
      'cityKuwaitCity' => l10n.cityKuwaitCity,
      'cityManama' => l10n.cityManama,
      'cityMuscat' => l10n.cityMuscat,
      'cityAmman' => l10n.cityAmman,
      'cityBeirut' => l10n.cityBeirut,
      'cityBaghdad' => l10n.cityBaghdad,
      'cityTehran' => l10n.cityTehran,
      'cityKarachi' => l10n.cityKarachi,
      'cityLahore' => l10n.cityLahore,
      'cityIslamabad' => l10n.cityIslamabad,
      'cityDelhi' => l10n.cityDelhi,
      'cityMumbai' => l10n.cityMumbai,
      'cityKualaLumpur' => l10n.cityKualaLumpur,
      'cityJakarta' => l10n.cityJakarta,
      'citySingapore' => l10n.citySingapore,
      'cityBangkok' => l10n.cityBangkok,
      'cityLondon' => l10n.cityLondon,
      'cityManchester' => l10n.cityManchester,
      'cityBirmingham' => l10n.cityBirmingham,
      'cityParis' => l10n.cityParis,
      'cityBerlin' => l10n.cityBerlin,
      'cityToronto' => l10n.cityToronto,
      'cityNewYork' => l10n.cityNewYork,
      'cityChicago' => l10n.cityChicago,
      'cityHouston' => l10n.cityHouston,
      'cityLosAngeles' => l10n.cityLosAngeles,
      'citySydney' => l10n.citySydney,
      'cityMelbourne' => l10n.cityMelbourne,
      _ => nameKey,
    };
